version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5436:5432'
volumes:
  postgres: