name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build
      continue-on-error: true

    - name: Docker build
      run: |
        docker build -t backend-blog-fiap .

    - name: Docker run
      run: |
        docker run -d -p 3000:3000 backend-blog-fiap
        sleep 10

    - name: Check application health
      run: |
        curl -f http://localhost:3000 || exit 1
